#!/bin/sh   
#
#ver20261001
#BOXABALAR
data_longa=$(date +%a_%d_%m_%Y__%H:%M);
equipo=`cat /etc/hostname`;

#ACTUALIZAR O CONTIDO DO REPOSITORIO DE SCRIPTS
sudo rm -f /var/tmp/posin;
sudo /usr/bin/wget -O /var/tmp/posin https://boxabalar.edu.xunta.gal/index.php/s/zEwjcBpCtQbJYYm/download/posin;
sudo chmod 755 /var/tmp/posin;
sudo rm -f /opt/actualizacion_*.txt;
sudo rm -f /opt/actualizacion_*.err;
sudo rm -f /var/tmp/actualizacion_*.txt;
sudo rm -f /var/tmp/actualizacion_*.err;
sudo sh /var/tmp/posin > /var/tmp/actualizacion_"$equipo"_$data_longa.txt 2> /var/tmp/actualizacion_"$equipo"_$data_longa.err;
#eliminar script posin
sudo rm -f /var/tmp/posin;
#sudo pkill -9 bash;
exit

