#!/bin/bash

if ! sudo git -C /opt/github pull;
    then
        CURRENT_BRANCH=$(sudo git -C /opt/github rev-parse --abbrev-ref HEAD);
        sudo git -C /opt/github reset --hard "origin/$CURRENT_BRANCH";
        sudo git -C /opt/github pull;
fi

