#!/bin/bash   
#
#ver20261001
#CAMBIAR CONTRASINAL DE ROOT
sudo passwd root;

#CLONAR/ACTUALIZAR CARTAFOL DE GITHUB
if [ ! -d /opt/github ];
    then
	    sudo sudo git clone https://github.com/tecnomgb/coordinacionTIC.git /opt/github;
        sudo chmod 755 -R /opt/github;
    else
        if ! sudo git -C /opt/github pull;
            then
                CURRENT_BRANCH=$(sudo git -C /opt/github rev-parse --abbrev-ref HEAD);
                sudo git -C /opt/github reset --hard "origin/$CURRENT_BRANCH";
                sudo git -C /opt/github pull;
                sudo chmod 755 -R /opt/github;
        fi
fi

#INSTALADOR DO SERVIZO DE ACTUALIZACIÓNS AUTOMÁTICAS DIARIAS
if [ ! -f /etc/systemd/system/actualizar.service ] || [ ! -f /etc/systemd/system/actualizar.timer ] || [ `egrep -c 'network-online' /etc/systemd/system/actualizar.service` = '0' ];
    then
        sudo systemctl stop actualizar.service;
        sudo cp -f /opt/github/abalinux12_mgb/ficheiros/actualizar.service /etc/systemd/system/actualizar.service;
        sudo cp -f /opt/github/abalinux12_mgb/ficheiros/actualizar.timer /etc/systemd/system/actualizar.timer;
		sudo chmod 755 /etc/systemd/system/actualiza*;
        sudo systemctl daemon-reload;
        sudo systemctl enable actualizar.timer;
        sudo systemctl start actualizar.timer;
        sudo systemctl start actualizar.service;
fi

