#!/bin/sh   
#
#ver20261001

echo "toor" | su - root -c "exit" &>/dev/null && echo "o contrasinal é toor"|| echo "o contrasinal non é toor"
echo "2o22.Maraca" | su - root -c "exit" &>/dev/null && echo "o contrasinal é 2o22.Maraca"|| echo "o contrasinal non é 2o22.Maraca"
